name:                BlockchainSim
version:             0.1.0.0
github:              "RKlompUU/BlockchainSim"
license:             GPL3
author:              "Rick Klomp"
maintainer:          "rick93nl@gmail.com"
copyright:           "2018 Rick Klomp"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/RKlompUU/BlockchainSim#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- algebraic-graphs
- unix

library:
  source-dirs: lib

executables:
  BlockchainSim-exe:
    main:                Main.hs
    source-dirs:         exe
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BlockchainSim

tests:
  BlockchainSim-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - BlockchainSim
